"""Initial schema - 12 models

Revision ID: b2542b2f7857
Revises: 
Create Date: 2025-11-26 19:40:34.891548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2542b2f7857'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ativo',
    sa.Column('id', sa.UUID(), nullable=False, comment='Identificador único do ativo'),
    sa.Column('ticker', sa.String(length=20), nullable=False, comment='Código/símbolo do ativo (ex: PETR4, AAPL, BTC)'),
    sa.Column('nome', sa.String(length=200), nullable=False, comment='Nome completo do ativo'),
    sa.Column('tipo', sa.Enum('ACAO', 'FII', 'REIT', 'BOND', 'ETF', 'CRIPTO', 'OUTRO', name='tipoativo'), nullable=False, comment='Tipo do ativo (ação, FII, REIT, bond, cripto)'),
    sa.Column('classe', sa.Enum('RENDA_VARIAVEL', 'RENDA_FIXA', 'CRIPTO', 'HIBRIDO', name='classeativo'), nullable=False, comment='Classe do ativo (renda variável, fixa, cripto)'),
    sa.Column('mercado', sa.String(length=10), nullable=False, comment='Mercado/país de negociação (BR, US, EUR)'),
    sa.Column('moeda', sa.String(length=3), nullable=False, comment='Moeda de negociação (BRL, USD, EUR)'),
    sa.Column('preco_atual', sa.Numeric(precision=18, scale=6), nullable=True, comment='Preço/cotação atual do ativo'),
    sa.Column('data_ultima_cotacao', sa.DateTime(timezone=True), nullable=True, comment='Data e hora da última cotação'),
    sa.Column('dividend_yield', sa.Numeric(precision=8, scale=4), nullable=True, comment='Dividend Yield em % (ex: 6.5000 = 6.5%)'),
    sa.Column('p_l', sa.Numeric(precision=10, scale=2), nullable=True, comment='Índice Preço/Lucro'),
    sa.Column('p_vp', sa.Numeric(precision=10, scale=2), nullable=True, comment='Índice Preço/Valor Patrimonial'),
    sa.Column('roe', sa.Numeric(precision=8, scale=4), nullable=True, comment='Return on Equity em %'),
    sa.Column('ativo', sa.Boolean(), nullable=False, comment='Indica se ativo está disponível para negociação'),
    sa.Column('deslistado', sa.Boolean(), nullable=False, comment='Indica se ativo foi deslistado da bolsa'),
    sa.Column('data_deslistagem', sa.Date(), nullable=True, comment='Data de deslistagem (se aplicável)'),
    sa.Column('observacoes', sa.Text(), nullable=True, comment='Observações e notas sobre o ativo'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Data de criação do registro'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Data da última atualização'),
    sa.CheckConstraint('length(nome) >= 2', name='ativo_nome_min_length'),
    sa.CheckConstraint('length(ticker) >= 1', name='ativo_ticker_min_length'),
    sa.CheckConstraint('preco_atual IS NULL OR preco_atual >= 0', name='ativo_preco_positivo'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'mercado', name='unique_ativo_ticker_mercado'),
    comment='Tabela de ativos financeiros (ações, FIIs, REITs, bonds, criptomoedas)'
    )
    op.create_index(op.f('ix_ativo_ativo'), 'ativo', ['ativo'], unique=False)
    op.create_index(op.f('ix_ativo_classe'), 'ativo', ['classe'], unique=False)
    op.create_index(op.f('ix_ativo_data_ultima_cotacao'), 'ativo', ['data_ultima_cotacao'], unique=False)
    op.create_index(op.f('ix_ativo_deslistado'), 'ativo', ['deslistado'], unique=False)
    op.create_index(op.f('ix_ativo_mercado'), 'ativo', ['mercado'], unique=False)
    op.create_index(op.f('ix_ativo_moeda'), 'ativo', ['moeda'], unique=False)
    op.create_index(op.f('ix_ativo_nome'), 'ativo', ['nome'], unique=False)
    op.create_index(op.f('ix_ativo_ticker'), 'ativo', ['ticker'], unique=False)
    op.create_index(op.f('ix_ativo_tipo'), 'ativo', ['tipo'], unique=False)
    op.create_table('feriado_mercado',
    sa.Column('id', sa.UUID(), nullable=False, comment='Identificador único do feriado'),
    sa.Column('pais', sa.String(length=2), nullable=False, comment='Código ISO do país (BR, US, etc.)'),
    sa.Column('mercado', sa.String(length=20), nullable=True, comment='Mercado/bolsa específica (B3, NYSE, NASDAQ, etc.) - NULL = todos'),
    sa.Column('data_feriado', sa.Date(), nullable=False, comment='Data do feriado'),
    sa.Column('tipo_feriado', sa.Enum('NACIONAL', 'BOLSA', 'PONTE', 'FECHAMENTO_ANTECIPADO', 'MANUTENCAO', 'OUTRO', name='tipoferiado'), nullable=False, comment='Tipo do feriado'),
    sa.Column('nome', sa.String(length=200), nullable=False, comment='Nome do feriado'),
    sa.Column('horario_fechamento', sa.Time(), nullable=True, comment='Horário de fechamento antecipado (se aplicável)'),
    sa.Column('recorrente', sa.Boolean(), nullable=False, comment='Indica se é feriado anual fixo (sempre no mesmo dia/mês)'),
    sa.Column('observacoes', sa.Text(), nullable=True, comment='Observações sobre o feriado'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Data de criação do registro'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Data da última atualização'),
    sa.CheckConstraint("pais ~* '^[A-Z]{2}$'", name='feriado_pais_iso_format'),
    sa.CheckConstraint('length(nome) >= 3', name='feriado_nome_min_length'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pais', 'mercado', 'data_feriado', name='unique_feriado_pais_mercado_data'),
    comment='Tabela de feriados e dias sem pregão nos mercados'
    )
    op.create_index(op.f('ix_feriado_mercado_data_feriado'), 'feriado_mercado', ['data_feriado'], unique=False)
    op.create_index(op.f('ix_feriado_mercado_mercado'), 'feriado_mercado', ['mercado'], unique=False)
    op.create_index(op.f('ix_feriado_mercado_pais'), 'feriado_mercado', ['pais'], unique=False)
    op.create_index(op.f('ix_feriado_mercado_recorrente'), 'feriado_mercado', ['recorrente'], unique=False)
    op.create_index(op.f('ix_feriado_mercado_tipo_feriado'), 'feriado_mercado', ['tipo_feriado'], unique=False)
    op.create_table('fonte_dados',
    sa.Column('id', sa.UUID(), nullable=False, comment='Identificador único da fonte'),
    sa.Column('nome', sa.String(length=100), nullable=False, comment='Nome da fonte de dados (ex: yfinance, Alpha Vantage)'),
    sa.Column('tipo_fonte', sa.Enum('API', 'SCRAPER', 'MANUAL', 'ARQUIVO', 'OUTRO', name='tipofontedados'), nullable=False, comment='Tipo da fonte de dados'),
    sa.Column('url_base', sa.String(length=500), nullable=True, comment='URL base da API ou site'),
    sa.Column('requer_autenticacao', sa.Boolean(), nullable=False, comment='Indica se requer chave API ou autenticação'),
    sa.Column('rate_limit', sa.String(length=50), nullable=True, comment="Limite de requisições (ex: '5/minute', '500/day')"),
    sa.Column('ativa', sa.Boolean(), nullable=False, comment='Indica se fonte está ativa'),
    sa.Column('prioridade', sa.Integer(), nullable=False, comment='Ordem de prioridade (1 = maior prioridade)'),
    sa.Column('ultima_consulta', sa.DateTime(timezone=True), nullable=True, comment='Timestamp da última consulta bem-sucedida'),
    sa.Column('total_consultas', sa.Integer(), nullable=False, comment='Total de consultas realizadas'),
    sa.Column('total_erros', sa.Integer(), nullable=False, comment='Total de erros encontrados'),
    sa.Column('observacoes', sa.Text(), nullable=True, comment='Observações sobre a fonte de dados'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Data de criação do registro'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Data da última atualização'),
    sa.CheckConstraint('length(nome) >= 2', name='fonte_nome_min_length'),
    sa.CheckConstraint('prioridade > 0', name='fonte_prioridade_positiva'),
    sa.CheckConstraint('total_consultas >= 0', name='fonte_consultas_positivas'),
    sa.CheckConstraint('total_erros >= 0', name='fonte_erros_positivos'),
    sa.PrimaryKeyConstraint('id'),
    comment='Tabela de fontes de dados externas (APIs, scrapers)'
    )
    op.create_index(op.f('ix_fonte_dados_ativa'), 'fonte_dados', ['ativa'], unique=False)
    op.create_index(op.f('ix_fonte_dados_nome'), 'fonte_dados', ['nome'], unique=True)
    op.create_index(op.f('ix_fonte_dados_prioridade'), 'fonte_dados', ['prioridade'], unique=False)
    op.create_index(op.f('ix_fonte_dados_tipo_fonte'), 'fonte_dados', ['tipo_fonte'], unique=False)
    op.create_index(op.f('ix_fonte_dados_ultima_consulta'), 'fonte_dados', ['ultima_consulta'], unique=False)
    op.create_table('regra_fiscal',
    sa.Column('id', sa.UUID(), nullable=False, comment='Identificador único da regra'),
    sa.Column('pais', sa.String(length=2), nullable=False, comment='Código ISO do país (BR, US, etc.)'),
    sa.Column('tipo_ativo', sa.String(length=20), nullable=True, comment='Tipo de ativo (ACAO, FII, REIT, BOND, etc.) - NULL = todos'),
    sa.Column('tipo_operacao', sa.String(length=20), nullable=True, comment='Tipo de operação (COMPRA, VENDA, DAY_TRADE, SWING_TRADE) - NULL = todas'),
    sa.Column('aliquota_ir', sa.Numeric(precision=6, scale=4), nullable=False, comment='Alíquota de IR em % (ex: 15.0000 = 15%)'),
    sa.Column('valor_isencao', sa.Numeric(precision=18, scale=2), nullable=True, comment='Valor de isenção mensal (ex: R$ 20.000,00 no Brasil)'),
    sa.Column('incide_sobre', sa.Enum('LUCRO', 'RECEITA', 'PROVENTO', 'OPERACAO', name='incidenciaimposto'), nullable=False, comment='Sobre o que incide o imposto'),
    sa.Column('descricao', sa.Text(), nullable=False, comment='Descrição detalhada da regra fiscal'),
    sa.Column('vigencia_inicio', sa.Date(), nullable=False, comment='Data de início da vigência da regra'),
    sa.Column('vigencia_fim', sa.Date(), nullable=True, comment='Data de fim da vigência (NULL = vigente indefinidamente)'),
    sa.Column('ativa', sa.Boolean(), nullable=False, comment='Indica se regra está ativa'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Data de criação do registro'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Data da última atualização'),
    sa.CheckConstraint("pais ~* '^[A-Z]{2}$'", name='regra_pais_iso_format'),
    sa.CheckConstraint('aliquota_ir >= 0 AND aliquota_ir <= 100', name='regra_aliquota_valida'),
    sa.CheckConstraint('valor_isencao IS NULL OR valor_isencao >= 0', name='regra_isencao_positiva'),
    sa.CheckConstraint('vigencia_fim IS NULL OR vigencia_fim >= vigencia_inicio', name='regra_vigencia_valida'),
    sa.PrimaryKeyConstraint('id'),
    comment='Tabela de regras tributárias por país e tipo de ativo'
    )
    op.create_index(op.f('ix_regra_fiscal_ativa'), 'regra_fiscal', ['ativa'], unique=False)
    op.create_index(op.f('ix_regra_fiscal_incide_sobre'), 'regra_fiscal', ['incide_sobre'], unique=False)
    op.create_index(op.f('ix_regra_fiscal_pais'), 'regra_fiscal', ['pais'], unique=False)
    op.create_index(op.f('ix_regra_fiscal_tipo_ativo'), 'regra_fiscal', ['tipo_ativo'], unique=False)
    op.create_index(op.f('ix_regra_fiscal_tipo_operacao'), 'regra_fiscal', ['tipo_operacao'], unique=False)
    op.create_index(op.f('ix_regra_fiscal_vigencia_fim'), 'regra_fiscal', ['vigencia_fim'], unique=False)
    op.create_index(op.f('ix_regra_fiscal_vigencia_inicio'), 'regra_fiscal', ['vigencia_inicio'], unique=False)
    op.create_table('usuario',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('nome_completo', sa.String(length=200), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'USER', 'READONLY', name='userrole'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuario_email'), 'usuario', ['email'], unique=True)
    op.create_index(op.f('ix_usuario_username'), 'usuario', ['username'], unique=True)
    op.create_table('corretora',
    sa.Column('id', sa.UUID(), nullable=False, comment='Identificador único da corretora'),
    sa.Column('usuario_id', sa.UUID(), nullable=False, comment='ID do usuário proprietário'),
    sa.Column('nome', sa.String(length=100), nullable=False, comment='Nome da corretora/exchange (ex: XP, Clear, Binance)'),
    sa.Column('tipo', sa.Enum('CORRETORA', 'EXCHANGE', name='tipocorretora'), nullable=False, comment='Tipo: corretora tradicional ou exchange cripto'),
    sa.Column('pais', sa.String(length=2), nullable=False, comment='Código ISO 3166-1 alpha-2 do país (BR, US, etc.)'),
    sa.Column('moeda_padrao', sa.String(length=3), nullable=False, comment='Código ISO 4217 da moeda (BRL, USD, EUR)'),
    sa.Column('saldo_atual', sa.Numeric(precision=18, scale=2), nullable=False, comment='Saldo disponível em caixa (na moeda padrão)'),
    sa.Column('ativa', sa.Boolean(), nullable=False, comment='Indica se conta está ativa'),
    sa.Column('observacoes', sa.Text(), nullable=True, comment='Observações e notas do usuário sobre a conta'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Data de criação do registro'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Data da última atualização'),
    sa.CheckConstraint("moeda_padrao ~* '^[A-Z]{3}$'", name='corretora_moeda_iso_format'),
    sa.CheckConstraint("pais ~* '^[A-Z]{2}$'", name='corretora_pais_iso_format'),
    sa.CheckConstraint('length(nome) >= 2', name='corretora_nome_min_length'),
    sa.CheckConstraint('saldo_atual >= 0', name='corretora_saldo_positivo'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', 'nome', 'pais', name='unique_corretora_usuario_nome_pais'),
    comment='Tabela de corretoras e contas de investimento'
    )
    op.create_index(op.f('ix_corretora_ativa'), 'corretora', ['ativa'], unique=False)
    op.create_index(op.f('ix_corretora_moeda_padrao'), 'corretora', ['moeda_padrao'], unique=False)
    op.create_index(op.f('ix_corretora_nome'), 'corretora', ['nome'], unique=False)
    op.create_index(op.f('ix_corretora_pais'), 'corretora', ['pais'], unique=False)
    op.create_index(op.f('ix_corretora_tipo'), 'corretora', ['tipo'], unique=False)
    op.create_index(op.f('ix_corretora_usuario_id'), 'corretora', ['usuario_id'], unique=False)
    op.create_table('evento_corporativo',
    sa.Column('id', sa.UUID(), nullable=False, comment='Identificador único do evento'),
    sa.Column('ativo_id', sa.UUID(), nullable=False, comment='ID do ativo afetado pelo evento'),
    sa.Column('ativo_novo_id', sa.UUID(), nullable=True, comment='ID do novo ativo (fusões, mudanças de ticker)'),
    sa.Column('tipo_evento', sa.Enum('SPLIT', 'GRUPAMENTO', 'BONIFICACAO', 'DIREITO_SUBSCRICAO', 'FUSAO', 'CISAO', 'INCORPORACAO', 'MUDANCA_TICKER', 'DESLISTAGEM', 'RELISTING', 'CANCELAMENTO', 'OUTRO', name='tipoeventocorporativo'), nullable=False, comment='Tipo do evento corporativo'),
    sa.Column('data_evento', sa.Date(), nullable=False, comment='Data do evento'),
    sa.Column('data_com', sa.Date(), nullable=True, comment='Data COM (último dia para ter direito ao evento)'),
    sa.Column('proporcao', sa.String(length=20), nullable=True, comment="Proporção do evento (ex: '2:1', '1:10', '1:1.5')"),
    sa.Column('descricao', sa.Text(), nullable=False, comment='Descrição detalhada do evento'),
    sa.Column('impacto_posicoes', sa.Boolean(), nullable=False, comment='Indica se as posições já foram ajustadas'),
    sa.Column('observacoes', sa.Text(), nullable=True, comment='Observações adicionais sobre o evento'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Data de criação do registro'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Data da última atualização'),
    #sa.CheckConstraint("\n            (tipo_evento IN ('split', 'grupamento', 'bonificacao') AND proporcao IS NOT NULL)\n            OR \n            (tipo_evento NOT IN ('split', 'grupamento', 'bonificacao'))\n            ", name='evento_proporcao_obrigatoria'),
    sa.CheckConstraint('data_com IS NULL OR data_com <= data_evento', name='evento_data_com_valida'),
    sa.ForeignKeyConstraint(['ativo_id'], ['ativo.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ativo_novo_id'], ['ativo.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    comment='Tabela de eventos corporativos que afetam ativos'
    )
    op.create_index(op.f('ix_evento_corporativo_ativo_id'), 'evento_corporativo', ['ativo_id'], unique=False)
    op.create_index(op.f('ix_evento_corporativo_ativo_novo_id'), 'evento_corporativo', ['ativo_novo_id'], unique=False)
    op.create_index(op.f('ix_evento_corporativo_data_com'), 'evento_corporativo', ['data_com'], unique=False)
    op.create_index(op.f('ix_evento_corporativo_data_evento'), 'evento_corporativo', ['data_evento'], unique=False)
    op.create_index(op.f('ix_evento_corporativo_impacto_posicoes'), 'evento_corporativo', ['impacto_posicoes'], unique=False)
    op.create_index(op.f('ix_evento_corporativo_tipo_evento'), 'evento_corporativo', ['tipo_evento'], unique=False)
    op.create_table('log_auditoria',
    sa.Column('id', sa.UUID(), nullable=False, comment='Identificador único do log'),
    sa.Column('usuario_id', sa.UUID(), nullable=True, comment='ID do usuário (NULL para ações anônimas)'),
    sa.Column('acao', sa.String(length=50), nullable=False, comment='Tipo de ação (LOGIN, LOGOUT, CREATE, UPDATE, DELETE, VIEW, EXPORT, etc.)'),
    sa.Column('entidade', sa.String(length=100), nullable=True, comment='Nome da entidade afetada (Usuario, Transacao, Posicao, etc.)'),
    sa.Column('entidade_id', sa.UUID(), nullable=True, comment='ID do registro afetado'),
    sa.Column('dados_antes', sa.JSON(), nullable=True, comment='Estado anterior do registro (JSON)'),
    sa.Column('dados_depois', sa.JSON(), nullable=True, comment='Estado posterior do registro (JSON)'),
    sa.Column('ip_address', sa.String(length=45), nullable=True, comment='Endereço IP de origem'),
    sa.Column('user_agent', sa.String(length=500), nullable=True, comment='User-Agent (navegador/cliente)'),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False, comment='Data/hora da ação'),
    sa.Column('sucesso', sa.Boolean(), nullable=False, comment='Indica se ação foi bem-sucedida'),
    sa.Column('mensagem', sa.Text(), nullable=True, comment='Mensagem de erro ou detalhes adicionais'),
    sa.CheckConstraint('length(acao) >= 3', name='log_acao_min_length'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    comment='Tabela de logs de auditoria para compliance'
    )
    op.create_index(op.f('ix_log_auditoria_acao'), 'log_auditoria', ['acao'], unique=False)
    op.create_index(op.f('ix_log_auditoria_entidade'), 'log_auditoria', ['entidade'], unique=False)
    op.create_index(op.f('ix_log_auditoria_entidade_id'), 'log_auditoria', ['entidade_id'], unique=False)
    op.create_index(op.f('ix_log_auditoria_ip_address'), 'log_auditoria', ['ip_address'], unique=False)
    op.create_index(op.f('ix_log_auditoria_sucesso'), 'log_auditoria', ['sucesso'], unique=False)
    op.create_index(op.f('ix_log_auditoria_timestamp'), 'log_auditoria', ['timestamp'], unique=False)
    op.create_index(op.f('ix_log_auditoria_usuario_id'), 'log_auditoria', ['usuario_id'], unique=False)
    op.create_table('provento',
    sa.Column('id', sa.UUID(), nullable=False, comment='Identificador único do provento'),
    sa.Column('ativo_id', sa.UUID(), nullable=False, comment='ID do ativo que pagou o provento'),
    sa.Column('tipo_provento', sa.Enum('DIVIDENDO', 'JCP', 'RENDIMENTO', 'CUPOM', 'BONIFICACAO', 'DIREITO_SUBSCRICAO', 'OUTRO', name='tipoprovento'), nullable=False, comment='Tipo do provento (dividendo, JCP, rendimento, etc.)'),
    sa.Column('valor_por_acao', sa.Numeric(precision=18, scale=6), nullable=False, comment='Valor unitário por ativo'),
    sa.Column('quantidade_ativos', sa.Numeric(precision=18, scale=8), nullable=False, comment='Quantidade de ativos que geraram o provento'),
    sa.Column('valor_bruto', sa.Numeric(precision=18, scale=2), nullable=False, comment='Valor bruto recebido'),
    sa.Column('imposto_retido', sa.Numeric(precision=18, scale=2), nullable=False, comment='IR retido na fonte'),
    sa.Column('valor_liquido', sa.Numeric(precision=18, scale=2), nullable=False, comment='Valor líquido creditado'),
    sa.Column('data_com', sa.Date(), nullable=False, comment='Data COM (último dia para ter direito ao provento)'),
    sa.Column('data_pagamento', sa.Date(), nullable=False, comment='Data efetiva do pagamento'),
    sa.Column('observacoes', sa.Text(), nullable=True, comment='Observações sobre o provento'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Data de criação do registro'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Data da última atualização'),
    sa.CheckConstraint('data_pagamento >= data_com', name='provento_data_pagamento_valida'),
    sa.CheckConstraint('imposto_retido >= 0', name='provento_imposto_positivo'),
    sa.CheckConstraint('quantidade_ativos > 0', name='provento_quantidade_positiva'),
    sa.CheckConstraint('valor_bruto > 0', name='provento_valor_bruto_positivo'),
    sa.CheckConstraint('valor_liquido <= valor_bruto', name='provento_liquido_menor_bruto'),
    sa.CheckConstraint('valor_liquido > 0', name='provento_valor_liquido_positivo'),
    sa.CheckConstraint('valor_por_acao > 0', name='provento_valor_por_acao_positivo'),
    sa.ForeignKeyConstraint(['ativo_id'], ['ativo.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    comment='Tabela de proventos recebidos (dividendos, JCP, rendimentos)'
    )
    op.create_index(op.f('ix_provento_ativo_id'), 'provento', ['ativo_id'], unique=False)
    op.create_index(op.f('ix_provento_data_com'), 'provento', ['data_com'], unique=False)
    op.create_index(op.f('ix_provento_data_pagamento'), 'provento', ['data_pagamento'], unique=False)
    op.create_index(op.f('ix_provento_tipo_provento'), 'provento', ['tipo_provento'], unique=False)
    op.create_table('movimentacao_caixa',
    sa.Column('id', sa.UUID(), nullable=False, comment='Identificador único da movimentação'),
    sa.Column('usuario_id', sa.UUID(), nullable=False, comment='ID do usuário'),
    sa.Column('corretora_id', sa.UUID(), nullable=False, comment='ID da corretora (origem)'),
    sa.Column('corretora_destino_id', sa.UUID(), nullable=True, comment='ID da corretora destino (apenas para transferências)'),
    sa.Column('provento_id', sa.UUID(), nullable=True, comment='ID do provento (apenas para crédito de provento)'),
    sa.Column('tipo_movimentacao', sa.Enum('DEPOSITO', 'SAQUE', 'TRANSFERENCIA_ENVIADA', 'TRANSFERENCIA_RECEBIDA', 'CREDITO_PROVENTO', 'PAGAMENTO_TAXA', 'PAGAMENTO_IMPOSTO', 'AJUSTE', 'OUTRO', name='tipomovimentacao'), nullable=False, comment='Tipo da movimentação'),
    sa.Column('valor', sa.Numeric(precision=18, scale=2), nullable=False, comment='Valor da movimentação'),
    sa.Column('moeda', sa.String(length=3), nullable=False, comment='Código ISO 4217 da moeda (BRL, USD, EUR)'),
    sa.Column('data_movimentacao', sa.Date(), nullable=False, comment='Data da movimentação'),
    sa.Column('descricao', sa.Text(), nullable=True, comment='Descrição da movimentação'),
    sa.Column('comprovante', sa.String(length=200), nullable=True, comment='Referência ao comprovante (número, hash, arquivo)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Data de criação do registro'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Data da última atualização'),
    #sa.CheckConstraint("\n            (tipo_movimentacao = 'credito_provento' AND provento_id IS NOT NULL)\n            OR \n            (tipo_movimentacao != 'credito_provento')\n            ", name='movimentacao_credito_tem_provento'),
    #sa.CheckConstraint("\n            (tipo_movimentacao IN ('transferencia_enviada', 'transferencia_recebida') \n             AND corretora_destino_id IS NOT NULL)\n            OR \n            (tipo_movimentacao NOT IN ('transferencia_enviada', 'transferencia_recebida'))\n            ", name='movimentacao_transferencia_tem_destino'),
    sa.CheckConstraint("moeda ~* '^[A-Z]{3}$'", name='movimentacao_moeda_iso_format'),
    sa.CheckConstraint('valor > 0', name='movimentacao_valor_positivo'),
    sa.ForeignKeyConstraint(['corretora_destino_id'], ['corretora.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['corretora_id'], ['corretora.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provento_id'], ['provento.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Tabela de movimentações de caixa em corretoras'
    )
    op.create_index(op.f('ix_movimentacao_caixa_corretora_destino_id'), 'movimentacao_caixa', ['corretora_destino_id'], unique=False)
    op.create_index(op.f('ix_movimentacao_caixa_corretora_id'), 'movimentacao_caixa', ['corretora_id'], unique=False)
    op.create_index(op.f('ix_movimentacao_caixa_data_movimentacao'), 'movimentacao_caixa', ['data_movimentacao'], unique=False)
    op.create_index(op.f('ix_movimentacao_caixa_moeda'), 'movimentacao_caixa', ['moeda'], unique=False)
    op.create_index(op.f('ix_movimentacao_caixa_provento_id'), 'movimentacao_caixa', ['provento_id'], unique=False)
    op.create_index(op.f('ix_movimentacao_caixa_tipo_movimentacao'), 'movimentacao_caixa', ['tipo_movimentacao'], unique=False)
    op.create_index(op.f('ix_movimentacao_caixa_usuario_id'), 'movimentacao_caixa', ['usuario_id'], unique=False)
    op.create_table('posicao',
    sa.Column('id', sa.UUID(), nullable=False, comment='Identificador único da posição'),
    sa.Column('usuario_id', sa.UUID(), nullable=False, comment='ID do usuário proprietário'),
    sa.Column('corretora_id', sa.UUID(), nullable=False, comment='ID da corretora onde está a posição'),
    sa.Column('ativo_id', sa.UUID(), nullable=False, comment='ID do ativo'),
    sa.Column('quantidade', sa.Numeric(precision=18, scale=8), nullable=False, comment='Quantidade de ativos (suporta fracionários)'),
    sa.Column('preco_medio', sa.Numeric(precision=18, scale=6), nullable=False, comment='Preço médio de aquisição'),
    sa.Column('custo_total', sa.Numeric(precision=18, scale=2), nullable=False, comment='Custo total investido (quantidade * preço médio)'),
    sa.Column('taxas_acumuladas', sa.Numeric(precision=18, scale=2), nullable=False, comment='Taxas de corretagem e custódia acumuladas'),
    sa.Column('impostos_acumulados', sa.Numeric(precision=18, scale=2), nullable=False, comment='Impostos pagos acumulados (IR, IOF, etc.)'),
    sa.Column('valor_atual', sa.Numeric(precision=18, scale=2), nullable=True, comment='Valor de mercado atual da posição'),
    sa.Column('lucro_prejuizo_realizado', sa.Numeric(precision=18, scale=2), nullable=False, comment='Lucro/prejuízo realizado em vendas'),
    sa.Column('lucro_prejuizo_nao_realizado', sa.Numeric(precision=18, scale=2), nullable=True, comment='Lucro/prejuízo não realizado (marcação a mercado)'),
    sa.Column('data_primeira_compra', sa.Date(), nullable=True, comment='Data da primeira aquisição deste ativo'),
    sa.Column('data_ultima_atualizacao', sa.DateTime(timezone=True), nullable=True, comment='Data da última atualização de valores'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Data de criação do registro'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Data da última atualização'),
    sa.CheckConstraint('custo_total >= 0', name='posicao_custo_total_positivo'),
    sa.CheckConstraint('impostos_acumulados >= 0', name='posicao_impostos_positivos'),
    sa.CheckConstraint('preco_medio >= 0', name='posicao_preco_medio_positivo'),
    sa.CheckConstraint('quantidade >= 0', name='posicao_quantidade_positiva'),
    sa.CheckConstraint('taxas_acumuladas >= 0', name='posicao_taxas_positivas'),
    sa.ForeignKeyConstraint(['ativo_id'], ['ativo.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['corretora_id'], ['corretora.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', 'corretora_id', 'ativo_id', name='unique_posicao_usuario_corretora_ativo'),
    comment='Tabela de posições em carteira (holdings)'
    )
    op.create_index(op.f('ix_posicao_ativo_id'), 'posicao', ['ativo_id'], unique=False)
    op.create_index(op.f('ix_posicao_corretora_id'), 'posicao', ['corretora_id'], unique=False)
    op.create_index(op.f('ix_posicao_data_primeira_compra'), 'posicao', ['data_primeira_compra'], unique=False)
    op.create_index(op.f('ix_posicao_data_ultima_atualizacao'), 'posicao', ['data_ultima_atualizacao'], unique=False)
    op.create_index(op.f('ix_posicao_usuario_id'), 'posicao', ['usuario_id'], unique=False)
    op.create_table('transacao',
    sa.Column('id', sa.UUID(), nullable=False, comment='Identificador único da transação'),
    sa.Column('usuario_id', sa.UUID(), nullable=False, comment='ID do usuário'),
    sa.Column('corretora_id', sa.UUID(), nullable=False, comment='ID da corretora'),
    sa.Column('ativo_id', sa.UUID(), nullable=False, comment='ID do ativo transacionado'),
    sa.Column('tipo_operacao', sa.Enum('COMPRA', 'VENDA', name='tipooperacao'), nullable=False, comment='Tipo de operação: COMPRA ou VENDA'),
    sa.Column('quantidade', sa.Numeric(precision=18, scale=8), nullable=False, comment='Quantidade transacionada (suporta fracionários)'),
    sa.Column('preco_unitario', sa.Numeric(precision=18, scale=6), nullable=False, comment='Preço por unidade'),
    sa.Column('valor_total', sa.Numeric(precision=18, scale=2), nullable=False, comment='Valor total da operação (quantidade * preço)'),
    sa.Column('taxas', sa.Numeric(precision=18, scale=2), nullable=False, comment='Taxas de corretagem, custódia, emolumentos'),
    sa.Column('impostos', sa.Numeric(precision=18, scale=2), nullable=False, comment='IR retido na fonte, IOF, etc.'),
    sa.Column('data_operacao', sa.Date(), nullable=False, comment='Data da operação'),
    sa.Column('data_liquidacao', sa.Date(), nullable=True, comment='Data de liquidação (D+2, D+3, etc.)'),
    sa.Column('observacoes', sa.Text(), nullable=True, comment='Observações sobre a transação'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Data de criação do registro'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Data da última atualização'),
    sa.CheckConstraint('data_liquidacao IS NULL OR data_liquidacao >= data_operacao', name='transacao_data_liquidacao_valida'),
    sa.CheckConstraint('impostos >= 0', name='transacao_impostos_positivos'),
    sa.CheckConstraint('preco_unitario > 0', name='transacao_preco_positivo'),
    sa.CheckConstraint('quantidade > 0', name='transacao_quantidade_positiva'),
    sa.CheckConstraint('taxas >= 0', name='transacao_taxas_positivas'),
    sa.CheckConstraint('valor_total > 0', name='transacao_valor_total_positivo'),
    sa.ForeignKeyConstraint(['ativo_id'], ['ativo.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['corretora_id'], ['corretora.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Tabela de transações de compra e venda de ativos'
    )
    op.create_index(op.f('ix_transacao_ativo_id'), 'transacao', ['ativo_id'], unique=False)
    op.create_index(op.f('ix_transacao_corretora_id'), 'transacao', ['corretora_id'], unique=False)
    op.create_index(op.f('ix_transacao_data_liquidacao'), 'transacao', ['data_liquidacao'], unique=False)
    op.create_index(op.f('ix_transacao_data_operacao'), 'transacao', ['data_operacao'], unique=False)
    op.create_index(op.f('ix_transacao_tipo_operacao'), 'transacao', ['tipo_operacao'], unique=False)
    op.create_index(op.f('ix_transacao_usuario_id'), 'transacao', ['usuario_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transacao_usuario_id'), table_name='transacao')
    op.drop_index(op.f('ix_transacao_tipo_operacao'), table_name='transacao')
    op.drop_index(op.f('ix_transacao_data_operacao'), table_name='transacao')
    op.drop_index(op.f('ix_transacao_data_liquidacao'), table_name='transacao')
    op.drop_index(op.f('ix_transacao_corretora_id'), table_name='transacao')
    op.drop_index(op.f('ix_transacao_ativo_id'), table_name='transacao')
    op.drop_table('transacao')
    op.drop_index(op.f('ix_posicao_usuario_id'), table_name='posicao')
    op.drop_index(op.f('ix_posicao_data_ultima_atualizacao'), table_name='posicao')
    op.drop_index(op.f('ix_posicao_data_primeira_compra'), table_name='posicao')
    op.drop_index(op.f('ix_posicao_corretora_id'), table_name='posicao')
    op.drop_index(op.f('ix_posicao_ativo_id'), table_name='posicao')
    op.drop_table('posicao')
    op.drop_index(op.f('ix_movimentacao_caixa_usuario_id'), table_name='movimentacao_caixa')
    op.drop_index(op.f('ix_movimentacao_caixa_tipo_movimentacao'), table_name='movimentacao_caixa')
    op.drop_index(op.f('ix_movimentacao_caixa_provento_id'), table_name='movimentacao_caixa')
    op.drop_index(op.f('ix_movimentacao_caixa_moeda'), table_name='movimentacao_caixa')
    op.drop_index(op.f('ix_movimentacao_caixa_data_movimentacao'), table_name='movimentacao_caixa')
    op.drop_index(op.f('ix_movimentacao_caixa_corretora_id'), table_name='movimentacao_caixa')
    op.drop_index(op.f('ix_movimentacao_caixa_corretora_destino_id'), table_name='movimentacao_caixa')
    op.drop_table('movimentacao_caixa')
    op.drop_index(op.f('ix_provento_tipo_provento'), table_name='provento')
    op.drop_index(op.f('ix_provento_data_pagamento'), table_name='provento')
    op.drop_index(op.f('ix_provento_data_com'), table_name='provento')
    op.drop_index(op.f('ix_provento_ativo_id'), table_name='provento')
    op.drop_table('provento')
    op.drop_index(op.f('ix_log_auditoria_usuario_id'), table_name='log_auditoria')
    op.drop_index(op.f('ix_log_auditoria_timestamp'), table_name='log_auditoria')
    op.drop_index(op.f('ix_log_auditoria_sucesso'), table_name='log_auditoria')
    op.drop_index(op.f('ix_log_auditoria_ip_address'), table_name='log_auditoria')
    op.drop_index(op.f('ix_log_auditoria_entidade_id'), table_name='log_auditoria')
    op.drop_index(op.f('ix_log_auditoria_entidade'), table_name='log_auditoria')
    op.drop_index(op.f('ix_log_auditoria_acao'), table_name='log_auditoria')
    op.drop_table('log_auditoria')
    op.drop_index(op.f('ix_evento_corporativo_tipo_evento'), table_name='evento_corporativo')
    op.drop_index(op.f('ix_evento_corporativo_impacto_posicoes'), table_name='evento_corporativo')
    op.drop_index(op.f('ix_evento_corporativo_data_evento'), table_name='evento_corporativo')
    op.drop_index(op.f('ix_evento_corporativo_data_com'), table_name='evento_corporativo')
    op.drop_index(op.f('ix_evento_corporativo_ativo_novo_id'), table_name='evento_corporativo')
    op.drop_index(op.f('ix_evento_corporativo_ativo_id'), table_name='evento_corporativo')
    op.drop_table('evento_corporativo')
    op.drop_index(op.f('ix_corretora_usuario_id'), table_name='corretora')
    op.drop_index(op.f('ix_corretora_tipo'), table_name='corretora')
    op.drop_index(op.f('ix_corretora_pais'), table_name='corretora')
    op.drop_index(op.f('ix_corretora_nome'), table_name='corretora')
    op.drop_index(op.f('ix_corretora_moeda_padrao'), table_name='corretora')
    op.drop_index(op.f('ix_corretora_ativa'), table_name='corretora')
    op.drop_table('corretora')
    op.drop_index(op.f('ix_usuario_username'), table_name='usuario')
    op.drop_index(op.f('ix_usuario_email'), table_name='usuario')
    op.drop_table('usuario')
    op.drop_index(op.f('ix_regra_fiscal_vigencia_inicio'), table_name='regra_fiscal')
    op.drop_index(op.f('ix_regra_fiscal_vigencia_fim'), table_name='regra_fiscal')
    op.drop_index(op.f('ix_regra_fiscal_tipo_operacao'), table_name='regra_fiscal')
    op.drop_index(op.f('ix_regra_fiscal_tipo_ativo'), table_name='regra_fiscal')
    op.drop_index(op.f('ix_regra_fiscal_pais'), table_name='regra_fiscal')
    op.drop_index(op.f('ix_regra_fiscal_incide_sobre'), table_name='regra_fiscal')
    op.drop_index(op.f('ix_regra_fiscal_ativa'), table_name='regra_fiscal')
    op.drop_table('regra_fiscal')
    op.drop_index(op.f('ix_fonte_dados_ultima_consulta'), table_name='fonte_dados')
    op.drop_index(op.f('ix_fonte_dados_tipo_fonte'), table_name='fonte_dados')
    op.drop_index(op.f('ix_fonte_dados_prioridade'), table_name='fonte_dados')
    op.drop_index(op.f('ix_fonte_dados_nome'), table_name='fonte_dados')
    op.drop_index(op.f('ix_fonte_dados_ativa'), table_name='fonte_dados')
    op.drop_table('fonte_dados')
    op.drop_index(op.f('ix_feriado_mercado_tipo_feriado'), table_name='feriado_mercado')
    op.drop_index(op.f('ix_feriado_mercado_recorrente'), table_name='feriado_mercado')
    op.drop_index(op.f('ix_feriado_mercado_pais'), table_name='feriado_mercado')
    op.drop_index(op.f('ix_feriado_mercado_mercado'), table_name='feriado_mercado')
    op.drop_index(op.f('ix_feriado_mercado_data_feriado'), table_name='feriado_mercado')
    op.drop_table('feriado_mercado')
    op.drop_index(op.f('ix_ativo_tipo'), table_name='ativo')
    op.drop_index(op.f('ix_ativo_ticker'), table_name='ativo')
    op.drop_index(op.f('ix_ativo_nome'), table_name='ativo')
    op.drop_index(op.f('ix_ativo_moeda'), table_name='ativo')
    op.drop_index(op.f('ix_ativo_mercado'), table_name='ativo')
    op.drop_index(op.f('ix_ativo_deslistado'), table_name='ativo')
    op.drop_index(op.f('ix_ativo_data_ultima_cotacao'), table_name='ativo')
    op.drop_index(op.f('ix_ativo_classe'), table_name='ativo')
    op.drop_index(op.f('ix_ativo_ativo'), table_name='ativo')
    op.drop_table('ativo')
    # ### end Alembic commands ###
